#spring.application.name=RHA
spring:
    application:
        name: RHA
    datasource:
        url: jdbc:postgresql://localhost:5432/RHA
        username: postgres
        password: "8585"
        driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
    server:
      address: 127.0.0.1
      port: 8080
      error:
        include-stacktrace: always